GamersGridApp/Controllers/GameController.cs
using GamersGridApp.Core;
using GamersGridApp.Core.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GamersGridApp.Controllers
{
    public class GameController : Controller
    {

        private readonly IUnitOfWork UnitOfWork;


        public GameController(IUnitOfWork unitofwork)
        {
            UnitOfWork = unitofwork;

        }
        // GET: Game
        public ViewResult Index()
        {
            var games = UnitOfWork.Games.GetGames().ToList();
            return View("Games", games);
            //return View("GamesList");
        }


        public ActionResult GameProfile(string gameName)
        {
            //if (gameName == null)
            //    return RedirectToAction("Index");

            //var game = dbContext.Games.SingleOrDefault(g => g.Title == gameName);

            //if(game == null)
            //    return RedirectToAction("Index");

            //testing
            //var gameTest = dbContext.Games.SingleOrDefault(g => g.Title.Contains(gameName));
            var gameTest = UnitOfWork.Games.GetGame(gameName);

            //var usersFocusing = dbContext.UserGameRelations.Where(g => g.Game.Title == gameTest.Title && g.IsFavoriteGame == true).Select(g => g.GameID).ToList();
            var usersFocusing = UnitOfWork.UserGames.GetGamesIdFocus(gameTest);

            var numberOfUsersFocusing = usersFocusing.Count();

            var profileGame = new ProfileGameViewModel()
            {
                Game = gameTest,
                UsersFocusing = numberOfUsersFocusing
            };
            return View(profileGame);
        }
    }
}

GamersGridApp/Controllers/UserController.cs
using GamersGridApp.Helpers;

using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using System.Data.Entity;
using GamersGridApp.Interfaces;
using GamersGridApp.Core;
using GamersGridApp.Core.ViewModels;
using GamersGridApp.Core.Models;

namespace GamersGridApp.Controllers
{
    public class UserController : Controller
    {
        private readonly IUnitOfWork UnitOfWork;



        public UserController(IUnitOfWork unitofwork)
        {
            UnitOfWork = unitofwork;


        }

        // GET: User
        public ViewResult Index()
        {

            return View("UsersList");
        }

        public ActionResult NewsFeed()
        {
            //Getting the user
            var userId = User.Identity.GetUserId();

            //var user = context.Users.Where(d => d.Id == userId).Select(d => d.UserAccount).SingleOrDefault();
            var user = UnitOfWork.GGUsers.GetLoggedUser(userId);

            //Getting All notifications
            //var notifications = context.UserNotifications
            //              .Where(un => un.UserId == user.ID && !un.IsRead)
            //              .Include(un => un.Notification)
            //              .Select(n => n.Notification)
            //              .ToList();

            var notifications = UnitOfWork.UserNotifications.GetUserNotifications(user.ID);

            List<INewsFeed> newsFeed = new List<INewsFeed>(notifications);
            return View(newsFeed.OrderBy(n => n.TimeStamp));
        }
        [Authorize]
        public ActionResult ProfilePage(int? userid)
        {
            //current logged user 
            var loggedUserId = User.Identity.GetUserId();
            //var currentLoggedUser = context.Users.Where(u => u.Id == loggedUserId).Select(u => u.UserAccount).SingleOrDefault();
            var currentLoggedUser = UnitOfWork.GGUsers.GetLoggedUser(loggedUserId);

            //var user = (userid == null) ? currentLoggedUser : context.GamersGridUsers.SingleOrDefault(u => u.ID == userid);
            var user = (userid == null) ? currentLoggedUser : UnitOfWork.GGUsers.GetUser(userid);

            //var favoritegame = context.UserGames.Where(d => d.UserId == userId).Select(d => d.UserAccount).SingleOrDefault();

            //var favoritegameID = context.UserGameRelations.Where(u => u.UserId == user.ID && u.IsFavoriteGame == true).Select(g => g.GameID).SingleOrDefault();
            var favoritegameID = UnitOfWork.Games.GetFavouriteGameId(user.ID);

            //var favoritegame = context.Games.Include(g => g.ID == favoritegameID).SingleOrDefault();

            //var favoritegame = context.Games
            //  .Where(g => g.ID == favoritegameID)
            //  .SingleOrDefault();
            if (favoritegameID == 0)
                favoritegameID = 3;
            var favoritegame = UnitOfWork.Games.GetFavouriteGame(favoritegameID);

            if (user == null)
                return HttpNotFound();

            //preparing viewmodel of searched user
            var viewModel = new UserProfilePageViewModel()
            {
                FollowsCount = UnitOfWork.Follows.GetFollowersCount(user.ID),
                FollowingCount = UnitOfWork.Follows.GetFollowingsCount(user.ID),
                User = user,
                FavouriteGame = favoritegame,
                FavoriteGameID = favoritegameID
            };

            //variables bound in viewmodel to be used for razor page logic between profile page and current logged user
            if (currentLoggedUser.ID == user.ID)
            {
                viewModel.IsCurrent = true;
                viewModel.LoggedUserId = currentLoggedUser.ID;
            }
            else
            {
                //var followRelation = context.Follows.SingleOrDefault(f => f.FollowerId == currentLoggedUser.ID && f.UserId == user.ID);
                var followRelation = UnitOfWork.Follows.GetFollowRelationOfTwoUsers(currentLoggedUser.ID, user.ID);
                if (followRelation == null)
                    viewModel.IsFollowing = false;
                else
                    viewModel.IsFollowing = true;

                viewModel.IsCurrent = false;
                viewModel.LoggedUserId = currentLoggedUser.ID;
            }
            //including stats 
            //var userGames = context.UserGameRelations
            //    .Where(u => u.UserId == user.ID)
            //    .Include(g => g.Game)
            //    .Include(ga => ga.GameAccount)
            //    .Include(gs => gs.GameAccount.GameAccountStats).ToList();

            var userGames = UnitOfWork.UserGames.GetUserGamesStats(user.ID);

            bool accountsFilled = true;

            foreach (var usergame in userGames)
            {
                if (usergame.GameAccount == null)
                    accountsFilled = false;
            }

            if (accountsFilled)
            {
                //viewModel.GamesStats = userGames
                //    .Where(u => u.UserId == user.ID)
                //    .Select(ga => ga.GameAccount.GameAccountStats)
                //    .ToDictionary(g => g.GameAccount.UserGame.Game.Title);

                viewModel.GamesStats = UnitOfWork.UserGames.GetGamesTitlesDict(userGames, user.ID);
            }

            return View(viewModel);
        }


        [Authorize]
        public ActionResult Customize()
        {
            var aspNetUserID = User.Identity.GetUserId();
            //var ggtUser = context.Users.Where(u => u.Id == aspNetUserID)
            //    .Select(c => c.UserAccount)
            //    .SingleOrDefault();
            var ggUser = UnitOfWork.GGUsers.GetLoggedUser(aspNetUserID);

            const int lolId = 1;
            const int dotaId = 2;
            const int overwatchId = 3;

            //var userGameRelationLol = context.UserGameRelations
            //    .Where(ugr => ugr.GameID == lolId && ugr.UserId == ggtUser.ID)
            //    .Include(ugr=>ugr.GameAccount)
            //    .SingleOrDefault();

            //var userGameRelationDota = context.UserGameRelations
            //   .Where(ugr => ugr.GameID == dotaId && ugr.UserId == ggtUser.ID)
            //   .Include(ugr => ugr.GameAccount)
            //   .SingleOrDefault();

            //var userGameRelationOverwatch = context.UserGameRelations
            //   .Where(ugr => ugr.GameID == overwatchId && ugr.UserId == ggtUser.ID)
            //   .Include(ugr => ugr.GameAccount)
            //   .SingleOrDefault();

            var userGameRelationLol = UnitOfWork.UserGames.GetUserGameRelationWithExistingGame(lolId, ggUser.ID);
            var userGameRelationDota = UnitOfWork.UserGames.GetUserGameRelationWithExistingGame(dotaId, ggUser.ID);
            var userGameRelationOverwatch = UnitOfWork.UserGames.GetUserGameRelationWithExistingGame(overwatchId, ggUser.ID);

            var viewmodel = new UserFormEditViewModel(ggUser, userGameRelationDota, userGameRelationLol, userGameRelationOverwatch);
            return View("Customize", viewmodel);

        }


        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Save(UserFormEditViewModel viewmodel, HttpPostedFileBase file)
        {
            //var userContent = context.GamersGridUsers
            //    .SingleOrDefault(u => u.ID == viewmodel.ID);
            var userContent = UnitOfWork.GGUsers.GetUser(viewmodel.ID);
            userContent.Update(
                viewmodel.FirstName, viewmodel.LastName, viewmodel.NickName,
                viewmodel.Description, viewmodel.Country, viewmodel.City);

            if (!(file is null))
            {
                userContent.Update(ExtraMethods.UploadPhoto(userContent.ID, file));
            }

            UnitOfWork.Complete();

            return RedirectToAction("ProfilePage", new { nickname = userContent.NickName });
        }
        //Get lolAccount
        public ActionResult LOLAccount()
        {
            //int lolID = context.Games
            //    .Where(g => g.Title == "League Of Legends")
            //    .Select(g => g.ID)
            //    .SingleOrDefault();
            int lolID = UnitOfWork.Games.GetGameId("League Of Legends");

            //check if the user is correct AspNetUser == User
            var appUserId = User.Identity.GetUserId();
            //var userContent = context.Users
            //    .Where(u => u.Id == appUserId)
            //    .Select(u => u.UserAccount)
            //    .Include(ug => ug.UserGames.Select(g => g.GameAccount))
            //    .SingleOrDefault();
            var userContent = UnitOfWork.GGUsers.GetUserContent(appUserId);

            //var userGame = userContent.UserGames.SingleOrDefault(g => g.Id == lolID);
            var userGame = UnitOfWork.Games.GetUserGameById(userContent, lolID);

            // instead of userGame != the check is done if a gameAcc exists or not
            if (userGame != null && userGame.GameAccount != null)
                return View(new AddLOLAccountViewmodel(userGame.GameAccount.NickName, userGame.GameAccount.AccountRegions));


            return View(new AddLOLAccountViewmodel());
        }
        ////Get OverWatch Account
        public ActionResult OverWatchAccount()
        {

            //int overwatchID = context.Games
            //    .Where(g => g.Title == "Overwatch")
            //    .Select(g => g.ID)
            //    .SingleOrDefault();
            int overwatchID = UnitOfWork.Games.GetGameId("Overwatch");


            var appUserId = User.Identity.GetUserId();
            //var userContent = context.Users
            //    .Where(u => u.Id == appUserId)
            //    .Select(u => u.UserAccount)
            //    .Include(ug => ug.UserGames.Select(g => g.GameAccount))
            //    .SingleOrDefault();

GamersGridApp/Views/Shared/_Footer.cshtml
@{
    ViewBag.Title = "_Footer";
}
<div class="container-footer">
    <footer class="container-fluid text-center foot">
        <div class="row">
            <div class="col-3 col-md-2">

            </div>
            <div class="col-6 col-md-8">
                <img class="footimg" src="~/Content/images/logo g2 w-02.png" alt="Logo">
            </div>
            <div class="col-3 col-md-2">
                <p class="white-txt small">
                    2020 Coding Bootcamp 9
                </p>
            </div>
        </div>
        
</footer>
</div>

GamersGridApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Gamer's Grid</title>
    <link rel="icon" href="@Url.Content("~/Content/Images/Icon/favicon.png")" />
    <link href="https://fonts.googleapis.com/css?family=Sen:400,700,800&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Josefin+Sans:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Bungee+Inline&display=swap" rel="stylesheet">
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/SiteCss")
    @Scripts.Render("~/bundles/modernizr")




</head>

<body>
    @Html.Partial("_NavBar")

    @if (!(ViewData["Title"].Equals("Home") || ViewData["Title"].Equals("Edit") || ViewData["Title"].Equals("Leaderboards") || ViewData["Title"].Equals("SeachEngine")))
    {

        <div class="container">
            @Html.Partial("_LoginSearchPartial")
        </div>
    }


    @if (ViewData["Title"].Equals("Home") || ViewData["Title"].Equals("Register") || ViewData["Title"].Equals("Login"))

    {
        @RenderBody()
        @Html.Partial("_Footer")

    }
    else
    {
        <div class="container container-main">
            <main role="main">
                @RenderBody()
                @Html.Partial("_Footer")
            </main>
        </div>
    }

    

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/underscore")
    @Scripts.Render("~/bundles/typeahead")
    @Scripts.Render("~/bundles/RegisterJs")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/loginnew")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/gameProfile")
    @Scripts.Render("~/bundles/app")



    <script src="~/Scripts/RegisterJs/jquery.validate.min.js"></script>

    @*@Scripts.Render("~/bundles/popper")*@
    @RenderSection("scripts", required: false)
    @if (User.Identity.IsAuthenticated)
    {
        <script src="/signalr/hubs"></script>

        <script type="text/x-template" id="notifications-template">
            <ul class="notifications">
                <%
                _.each(notifications, function(notification) { %>
                <li>
                    <%= notification.content %>
                </li>
                <% }) %>
            </ul>
        </script>

        <script type="text/x-template" id="notification-template">
            <ul class="notifications">
                <li>
                    <%= notification.content %>
                </li>
            </ul>
        </script>

        <script>
            $(document).ready(function () {
                let countElement = $(".js-notifications-count");
                let badgeElement = $(".notifications");
                NotificationsController.startNotifications(countElement, badgeElement);
                //let userid = $(".persistent-id").attr("id");
                //NotificationsController.enableSignalR(userid, countElement, badgeElement);
            });
        </script>
    }

</body>

</html>

GamersGridApp/Views/Shared/_LayoutAfterLogin.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/Bootstrap.css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">
            <img src="~/Content/Images/logo_small.png" alt="LOGO" style="height:36px;">
            Gamer's Grid
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ml-auto">

                <li class="nav-item">
                    <a class="nav-link" href="#">Games</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">How it works</a>
                </li>

            </ul>

            @using (Html.BeginForm("Search", "User", FormMethod.Get))
            {
                @Html.TextBox("searchString", null, new { @class = "form-control" })
            }

            <a class="nav-link" href="#">
                <img src="~/Content/Images/settings.png" alt="Settings" style="height:20px;">
            </a>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/mainLib")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

GamersGridApp/Views/Shared/_LoginSearchPartial.cshtml
@{
    ViewBag.Title = "_LoginSearchPartial";
}

@{
    ViewBag.SearchResult = "";
}

@using Microsoft.AspNet.Identity
@if (Request.IsAuthenticated)
{

    <div id="searchBarWrap" class="center">
        @{
            string url = "/Home/Search/";
        }
        <form action=@url>
            <input class="typeahead form-control searchBar" id="Search" type="text" name="searchString" placeholder="Search by User,Game" />
            <button type="submit" class="btn btn-default btn-circle">
                <span class="glyphicon glyphicon-search white" aria-hidden="true"></span>
            </button>
        </form>

    </div>

}



@section Scripts{
    <script>
        function SearchSmth() {
            document.getElementsById('#Search').keydown(function (event) {
                console.log('log1')
                var search = ('.searchBar').value;
                if (event.which == 13) {
                    window.location.href = window.document + '/home/search?searchString=' + search;
                    location.href = window.document.codeform.code.value + '.html';
                }
            })
        };
    </script>

}

GamersGridApp/Views/Shared/_NavBar.cshtml
@{
    ViewBag.SearchResult = "";
}



<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            @Html.ActionLink("GAMERS' GRID", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav navbar-left">
                <li>@Html.ActionLink("Players", "Gamers", "Home")</li>
                <li>@Html.ActionLink("Games", "Index", "Game")</li>
                <li>@Html.ActionLink("Leaderboard", "Leaderboards", "Home")</li>
                <li>@Html.ActionLink("Search Engine", "SearchEngine", "Home")</li>

            </ul>
            @Html.Partial("_LoginPartial")
        </div>
    </div>
</div>


@*<nav class="navbar navbar-expand-lg navbar-dark  fixed-top" style="background-color: hsl(225, 40%, 18%);">
        <a class="navbar-brand" href="#">
            <img src="~/Content/Images/logo_small.png" alt="LOGO" style="height:36px;">
            Gamer's Grid
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            @{
                string url = "/Home/Search/";
            }
            <ul class="navbar-nav ml-auto ">
                <li class="nav-item">
                    <form action=@url>
                        Typeahead Section
                        <input id="Search" class="typeahead form-control searchBar" type="text" name="searchString" />
                        <input type="submit" style="display: none" />
                    </form>
                </li>
                <li class="nav-item">
                    @Html.ActionLink("Users", "Index", "User", null, new { @class = "nav-link" })
                </li>
                <li class="nav-item">
                    @Html.ActionLink("Games", "Index", "Game", null, new { @class = "nav-link" })
                </li>

                @if (Request.IsAuthenticated)
                {
                    <li class="nav-item">
                        @Html.ActionLink("NewsFeed", "NewsFeed", "User", null, new { @class = "nav-link" })
                    </li>
                    <li class="nav-item">
                        @Html.ActionLink("My Profile", "ProfilePage", "User", null, new { @class = "nav-link" })
                    </li>
                    <li class="notifications">
                        <a href="#">
                            <i class="fas fa-headset"></i>
                            <span class="badge js-notifications-count hide"></span>
                        </a>
                    </li>
                    <li class="nav-item">
                        @Html.ActionLink("Messages", "MessageBoard", "Message", null, new { @class = "nav-link" })
                    </li>
                    <li class="nav-item">
                        <div class="dropdown show">
                            <a class="nav-link dropdown-toggle" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" href="#">
                                <i class="fas fa-cogs"></i>
                            </a>
                            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuLink">
                                @Html.ActionLink("Customize", "EditAvraam", "User", null, new { @class = "dropdown-item" })

                                <a class="dropdown-item" href="#">Another action</a>
                                <div class="dropdown-divider"></div>
                                @using (Html.BeginForm("LogOff", "Account", FormMethod.Post, new { id = "logoutForm", @class = "navbar-right" }))
                                {
                                    @Html.AntiForgeryToken()


                                    <a href="javascript:document.getElementById('logoutForm').submit()" class="dropdown-item">Log off</a>
                                }
                            </div>
                        </div>
                    </li>


                    using (Html.BeginForm("LogOff", "Account", FormMethod.Post, new { id = "logoutForm", @class = "navbar-right" }))
                    {
                        @Html.AntiForgeryToken()


                        <li class="nav-item">
                            <a href="javascript:document.getElementById('logoutForm').submit()" class="nav-link">Log off</a>
                        </li>
                    }
                }
                else
                {

                    <li class="nav-item">
                        @Html.ActionLink("Register", "Register", "Account", null, new { @class = "nav-link" })
                    </li>
                    <li class="nav-item">
                        @Html.ActionLink("Login", "Login", "Account", null, new { @class = "nav-link" })
                    </li>
                }

            </ul>

        </div>
    </nav>*@
@*@section Scripts{
        <script>
            function SearchSmth() {
                document.getElementsByClassName('searchBar').keydown(function (event) {
                    console.log('log1')
                    var search = ('.searchBar').value;
                    if (event.which == 13) {
                        window.location.href = window.document + '/home/search?searchString=' + search;
                        location.href = window.document.codeform.code.value + '.html';
                    }
                })
            };
    //        var url = document.getElementsByClassName("searchBar").value;
    //console.log(url);
    //console.log('Hello World!');
    //function() {
    //    console.log(10);
    //}
        </script>

}*@