GamersGrid/Controllers/GamerProfileController.cs
using GamersGrid.BLL;
using GamersGrid.DAL;
using GamersGrid.DAL.Models;
using GamersGrid.DAL.Models.Identity;
using GamersGrid.Helpers;
using GamersGrid.Models.User;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace GamersGrid.Controllers
{
    [Authorize]
    public class GamerProfileController : Controller
    {
        private readonly SignInManager<GGuser> _signInManager;
        private readonly UserManager<GGuser> _userManager;
        private readonly ILogger<GamerProfileController> _logger;
        private readonly CustomHelperService _helperService;
        private readonly IUnitOfWork unitOfWork;

        public GamerProfileController(ILogger<GamerProfileController> logger,
            SignInManager<GGuser> signInManager,
            UserManager<GGuser> userManager,
            CustomHelperService helperService,
            IUnitOfWork workUnit)
        {
            _logger = logger;
            _signInManager = signInManager;
            _userManager = userManager;
            _helperService = helperService;
            unitOfWork = workUnit;
        }
        //public IActionResult Index()
        //{

        //    return View("UsersList");
        //}

        [HttpGet]
        public async Task<ActionResult> Index(int? userid)
        {
            //Get currently logged user
            var currentLoggedUser = await _userManager.GetUserAsync(User);

            //identify if parameter "userid" is of logged user or another one, and fetch his profile
            var user = (userid == null) ? currentLoggedUser : unitOfWork.GGUsers.GetUser(userid);

            if (user == null)
                return NotFound();

            //Get user's favorite game
            var userGameRelation = await unitOfWork.UsersGamesRelations
                .GetFirstOrDefault(ugr => ugr.UserId == user.Id && ugr.IsFavoriteGame);

            var favoriteGame = await unitOfWork.Games.Get(userGameRelation.GameId);


            //preparing viewmodel of searched user
            var viewModel = new UserProfilePageVM()
            {
                FollowsCount = await unitOfWork.FollowRelations.GetFollowersCount(user.Id),
                FollowingCount = await unitOfWork.FollowRelations.GetFollowingsCount(user.Id),
                User = user,
                FavouriteGame = favoriteGame,
                FavoriteGameID = favoriteGame.Id
            };

            //variables bound in viewmodel to be used for razor page logic between profile page and current logged user
            if (currentLoggedUser.Id == user.Id)
            {
                viewModel.IsCurrent = true;
                viewModel.LoggedUserId = currentLoggedUser.Id;
            }
            else
            {
                //var followRelation = context.Follows.SingleOrDefault(f => f.FollowerId == currentLoggedUser.ID && f.UserId == user.ID);
                var followRelation = await unitOfWork.FollowRelations.GetFollowRelationOfTwoUsers(currentLoggedUser.Id, user.Id);
                if (followRelation == null)
                    viewModel.IsFollowing = false;
                else
                    viewModel.IsFollowing = true;

                viewModel.IsCurrent = false;
                viewModel.LoggedUserId = currentLoggedUser.Id;
            }

            //Get game accounts of user and their stats
            var gameAccounts = await unitOfWork.GameAccounts.GetAll(gameAccount => gameAccount.UserId == user.Id, includeProperties: "Statistics,Game");

            var gameStatsMappings = new Dictionary<string, GameAccountStats>();
            foreach (var gameAccount in gameAccounts)
            {
                gameStatsMappings.Add(gameAccount.Game.Title, gameAccount.Statistics);
            }
            viewModel.GamesStats = gameStatsMappings;


            return View(viewModel);
        }

        [HttpGet]
        public async Task<IActionResult> Edit()
        {
            //Get currently logged user
            var currentLoggedUser = await _userManager.GetUserAsync(User);

            var userGameAccounts = await unitOfWork.GameAccounts.GetAll(gameAccount => gameAccount.UserId == currentLoggedUser.Id);

            var userEditVM = new UserEditVM(currentLoggedUser, userGameAccounts.ToList());

            return View("Edit", userEditVM);
        }


        [HttpPost]
        //[ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(UserEditVM model)
        {
            if (ModelState.IsValid)
            {
                var user = await _userManager.GetUserAsync(User);
                user.Update(
                    model.FirstName, model.LastName, model.NickName,
                    model.Description, model.Country, model.City);

                if (model.AvatarImage != null)
                    user.UpdateAvatar(await _helperService.SaveAvatar(model.AvatarImage, user.Avatar));

                await unitOfWork.Save();

            }

            return RedirectToAction("Edit", model);
        }

        [HttpGet]
        public async Task<IActionResult> TestHub()     
        {
            return View();
        }

    }
}

GamersGrid/Controllers/MessageController.cs
using GamersGrid.BLL;
using GamersGrid.DAL.Models;
using GamersGrid.DAL.Models.Identity;
using GamersGrid.Models.Messageboard;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace GamersGrid.Controllers
{
    [Authorize]
    public class MessageController : Controller
    {

        private readonly SignInManager<GGuser> _signInManager;
        private readonly UserManager<GGuser> _userManager;
        private readonly ILogger<MessageController> _logger;
        private readonly IUnitOfWork unitOfWork;

        public MessageController(ILogger<MessageController> logger,
            SignInManager<GGuser> signInManager,
            UserManager<GGuser> userManager,
            IUnitOfWork uow)
        {
            _logger = logger;
            unitOfWork = uow;
            _signInManager = signInManager;
            _userManager = userManager;
        }


        public async Task<IActionResult> MessageBoard()
        {

            var currentUser = await _userManager.GetUserAsync(User);
            var messageChats = await unitOfWork.db.UserChatGroups
                .Include(ucg => ucg.Group)
                .Include(ucg => ucg.Group.UserChatGroups)
                .ThenInclude(ucg=>ucg.User)
                .Include(ucg => ucg.Group.Messages)
                .ThenInclude(m=>m.User)
                .Where(ucg => ucg.UserId == currentUser.Id)
                .Select(ucg => ucg.Group)
                .ToListAsync();


            if (messageChats.Count != 0)
            {
                var currentChat = messageChats.FirstOrDefault();
                var viewmodel = new MessageboardVM(messageChats, currentChat.Id, currentUser.NickName);
                return View(viewmodel);
            }
            else
            {
                var viewmodel = new MessageboardVM( currentUser.NickName);
                return View(viewmodel);
            }
        }

        [HttpGet]
        public async Task<IActionResult> FindMessageChats(int ID)
        {
            var currentUser = await _userManager.GetUserAsync(User);
            var RequestedUser =  unitOfWork.GGUsers.GetUser(ID);

            var chatGroup = await unitOfWork.db.ChatGroups
                .Where(cg =>
                cg.UserChatGroups.Any(ucg => ucg.UserId == currentUser.Id) &&
                cg.UserChatGroups.Any(ucg => ucg.UserId == RequestedUser.Id))
                .Include(cg => cg.Messages)
                .FirstOrDefaultAsync();


            if (chatGroup == null)
            {
                 chatGroup = new ChatGroup()
                {
                    Name = RequestedUser.NickName,
                    UserChatGroups = new List<UserChatGroup>(),
                    Messages = new List<Message>()
                };

                var chatGroupRelation1 = new UserChatGroup()
                {
                    User = currentUser,
                    Group = chatGroup
                };

                var chatGroupRelation2 = new UserChatGroup()
                {
                    User = RequestedUser,
                    Group = chatGroup
                };

                chatGroup.UserChatGroups.Add(chatGroupRelation1);
                chatGroup.UserChatGroups.Add(chatGroupRelation2);

                unitOfWork.db.ChatGroups.Add(chatGroup);
                await unitOfWork.Save();


                chatGroup = await unitOfWork.db.ChatGroups
                .Where(cg =>
                cg.UserChatGroups.Any(ucg => ucg.UserId == currentUser.Id) &&
                cg.UserChatGroups.Any(ucg => ucg.UserId == RequestedUser.Id))
                .Include(cg => cg.Messages)
                .FirstOrDefaultAsync();


            }
            var viewModel = new ChatGroupVM { Group = chatGroup, CurrentUserNickName = currentUser.NickName, CurrentMessageChatID = chatGroup.Id };

            return PartialView("_ChatBox", viewModel);
        }

        public async Task<IActionResult> GetPartial(int chatId)
        {
            var currentUser = await _userManager.GetUserAsync(User);
            //db.Users.Where(u => u.Id == aspNetUserId).Select(u => u.UserAccount).SingleOrDefault();
            var chatGroup = await unitOfWork.db.ChatGroups.Where(cg => cg.Id == chatId)
                .Include(cg=>cg.Messages)
                .FirstOrDefaultAsync();


            var viewModel = new ChatGroupVM { Group = chatGroup, CurrentUserNickName = currentUser.NickName, CurrentMessageChatID = chatGroup.Id };


            return PartialView("_ChatBox", viewModel);
        }


        public async Task<IActionResult> ChatWith(int currentUserId, int requestedUserID)
        {
            var followRelation1 = unitOfWork.FollowRelations.GetFollowRelationOfTwoUsers(currentUserId, requestedUserID);
            var followRelation2 = unitOfWork.FollowRelations.GetFollowRelationOfTwoUsers(requestedUserID, currentUserId);

            if (followRelation1 == null || followRelation2 == null)
                return NotFound();

            var currentUser = unitOfWork.GGUsers.GetUser(currentUserId);
            var RequestedUser = unitOfWork.GGUsers.GetUser(requestedUserID);

            var chatGroup = await unitOfWork.db.ChatGroups
                .Where(cg =>
                cg.UserChatGroups.Any(ucg => ucg.UserId == currentUser.Id) &&
                cg.UserChatGroups.Any(ucg => ucg.UserId == RequestedUser.Id))
                .Include(cg => cg.Messages)
                .FirstOrDefaultAsync();


            if (chatGroup == null)
            {
                chatGroup = new ChatGroup()
                {
                    Name = RequestedUser.NickName,
                    UserChatGroups = new List<UserChatGroup>(),
                    Messages = new List<Message>()
                };

                var chatGroupRelation1 = new UserChatGroup()
                {
                    User = currentUser,
                    Group = chatGroup
                };

                var chatGroupRelation2 = new UserChatGroup()
                {
                    User = RequestedUser,
                    Group = chatGroup
                };

                chatGroup.UserChatGroups.Add(chatGroupRelation1);
                chatGroup.UserChatGroups.Add(chatGroupRelation2);

                unitOfWork.db.ChatGroups.Add(chatGroup);
                await unitOfWork.Save();


                chatGroup = await unitOfWork.db.ChatGroups
                .Where(cg =>
                cg.UserChatGroups.Any(ucg => ucg.UserId == currentUser.Id) &&
                cg.UserChatGroups.Any(ucg => ucg.UserId == RequestedUser.Id))
                .Include(cg => cg.Messages)
                .FirstOrDefaultAsync();


            }


            var chatGroupsOfCurrentUser = await unitOfWork.db.UserChatGroups
                .Where(ucg => ucg.UserId == currentUser.Id)
                .Include(ucg => ucg.Group)
                .ThenInclude(g => g.Messages)
                .Select(ucg => ucg.Group)
                .ToListAsync();

            var viewModel = new MessageboardVM(chatGroupsOfCurrentUser, chatGroup.Id, currentUser.NickName);


            return View("MessageBoard", viewModel);
        }

    }
}

GamersGrid/Views/GamerProfile/Index.cshtml
@model GamersGrid.Models.User.UserProfilePageVM
@{
    ViewBag.Title = "ProfilePage";

}

@section Styles {
    <link href="~/css/Profile/Index.css" rel="stylesheet" type="text/css" />
    <link href="~/lib/toastr/css/toastr.min.css" rel="stylesheet" type="text/css" />
}

@{
    string followText;
    if (Model.IsFollowing)
    {
        followText = "UnFollow";
    }
    else
    {
        followText = "Follow";
    }

}

<div class="container profile-container">
    <div class="row">
        <div class="col-xs-12 col-sm-9">

            <!-- User profile -->
            @Html.HiddenFor(m => m.User.Id, new { id = "profileId" })
            @Html.HiddenFor(m => m.LoggedUserId, new { id = "loggedUserId" })
            <div class="panel panel-default">
                <div class="panel-body">
                    <div class="row">

                    </div>
                    <div class="profile__avatar col-xs-12 col-sm-5">
                        <img src="@((Model.User.Avatar == "nofile.png" || @String.IsNullOrWhiteSpace(Model.User.Avatar)) ? "/Static/Images/gamerdefault.jpg" : $"/UsersAvatars/{Model.User.Avatar}")">
                    </div>
                    <div class="profile__header col-xs-12 col-sm-7">
                        <h2>@Html.DisplayFor(u => u.User.FirstName) @Html.DisplayFor(u => u.User.LastName)</h2>
                        <h3><small>@Html.DisplayFor(u => u.User.NickName)</small></h3>
                        <h4>Favorite game:</h4>
                        <h4><strong>@Html.DisplayFor(u => u.FavouriteGame.Title)</strong></h4>
                        <h4>My quote:</h4>
                        <p class="text-muted">
                            @if (String.IsNullOrWhiteSpace(Model.User.Description))
                            {
                            <p style="color:#c4c4c4"><i>No quote yet</i></p>

                        }
                        else
                        {
                            <h4><strong>@Model.User.Description</strong></h4>
                        }

                            </>
                        </div>
                    </div>
                </div>
                @if (Model.GamesStats != null)
                {
                    foreach (var gameStats in Model.GamesStats)
                    {
                        {
                            int sum = gameStats.Value.Wins + gameStats.Value.Losses;
                            string width = ((double)gameStats.Value.Wins / (double)sum * 100).ToString("0,00") + "%";
                            string tierIcon = gameStats.Key == "League Of Legends" ? "/Content/Images/Games/LOLIcons/tier-icons-base/" + gameStats.Value.GetLOLRank() :
                                gameStats.Key == "Overwatch" ? "/Content/Images/Games/OverwatchIcons/" + gameStats.Value.GetOverWatchRank() :
                                "/Content/Images/Games/DotaIcons/" + gameStats.Value.GetDota2Rank();

                            <div class="panel panel-default">
                                <h2 class="panel-title"><strong>@gameStats.Key</strong></h2>
                                <div class="row">
                                    <div class="panel-heading col-xs-3">
                                        <img src=@tierIcon id="league-rank-icon" class="img-responsive">
                                    </div>
                                    <div class="panel-body col-xs-9">
                                        <table class="table profile__table">
                                            <tbody>
                                                <tr>
                                                    <th><strong>Rank</strong></th>
                                                    <td>@gameStats.Value.Rank</td>
                                                </tr>
                                                <tr>
                                                    <th><strong>Wins</strong></th>
                                                    <td>
                                                        <div class="progress">
                                                            <div class="progress-bar progress-bar-purple" role="progressbar" aria-valuenow="@gameStats.Value.Wins" aria-valuemin="0" aria-valuemax="@sum" style="width: @width;">
                                                                @gameStats.Value.Wins
                                                            </div>
                                                        </div>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <th><strong>KDA</strong></th>
                                                    <td>@gameStats.Value.KDA</td>
                                                </tr>
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>
                        }
                    }
                }
                <!-- Game 1 -->
                <!-- <div>Static Fields</div>

                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h2 class="panel-title"><strong>DOTA</strong></h2>
                    </div>
                    <div class="panel-body">
                        <table class="table profile__table">
                            <tbody>
                                <tr>
                                    <th><strong>Level</strong></th>
                                    <td>456</td>
                                </tr>
                                <tr>
                                    <th><strong>Stat 1</strong></th>
                                    <td>
                                        <div class="progress">
                                            <div class="progress-bar progress-bar-purple" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 60%;">
                                                60
                                            </div>
                                        </div>
                                    </td>
                                </tr>
                                <tr>
                                    <th><strong>Stat 2</strong></th>
                                    <td>234</td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>

                       <div class="panel panel-default">
                           <div class="panel-heading">
                               <h2 class="panel-title"><strong>Overwatch</strong></h2>
                           </div>
                           <div class="panel-body">
                               <table class="table profile__table">
                                   <tbody>
                                       <tr>
                                           <th><strong>Level</strong></th>
                                           <td>456</td>
                                       </tr>
                                       <tr>
                                           <th><strong>Stat 1</strong></th>
                                           <td>
                                               <div class="progress">
                                                   <div class="progress-bar progress-bar-purple" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 60%;">
                                                       60
                                                   </div>
                                               </div>
                                           </td>
                                       </tr>
                                       <tr>
                                           <th><strong>Stat 2</strong></th>
                                           <td>234</td>
                                       </tr>
                                   </tbody>
                               </table>
                           </div>
                       </div>
                       -->
            </div>
            <div class="col-xs-12 col-sm-3">

                @{
                    if (!Model.IsCurrent)
                    {
                        <!-- Contact user -->
                        <p>
                            <a id="followbtn" href="#" class="profile__contact-btn btn btn-lg btn-block btn-info" data-toggle="modal" data-target="#profile__contact-form">@followText</a>
                        </p>
                        <p>
                            <button id="messageBtn" class="profile__contact-btn btn btn-lg btn-block btn-info" data-toggle="modal" data-target="#profile__contact-form" data-redirect-url="@Url.Action("ChatWith","Message", new { currentUserId = Model.LoggedUserId , requestedUserId= Model.User.Id})">
                                Message me
                            </button>
                        </p>
                    }
                    else
                    {
                        <p>
                            @Html.ActionLink("Customize", "Edit", "GamerProfile", null, new { @class = "profile__contact-btn btn btn-lg btn-block btn-info" })

                        </p>

                    }

                }


                <div class="profile_follow">
                    <div class="profile_followers">
                        <p>FOLLOWERS</p>
                        <h3 id="followersCount"><strong>@Model.FollowsCount</strong></h3>

                    </div>
                    <div class="profile_followees">
                        <p>FOLLOWING</p>
                        <h3>@Model.FollowingCount</h3>
                    </div>
                </div>


                <hr class="profile__contact-hr">

                <!-- Contact info -->
                <div class="profile__contact-info">
                    <div class="profile__contact-info-item">

                        <div class="profile__contact-info-body">
                            <h5 class="profile__contact-info-heading">Country</h5>
                            @Html.DisplayFor(u => u.User.Country)
                        </div>
                    </div>
                    <div class="profile__contact-info-item">
                        <div class="profile__contact-info-body">
                            <h5 class="profile__contact-info-heading">City</h5>
                            @Html.DisplayFor(u => u.User.City)
                        </div>
                    </div>
                    @*<div class="profile__contact-info-item">
                            <div class="profile__contact-info-icon">
                                <i class="fa fa-envelope-square"></i>
                            </div>
                            <div class="profile__contact-info-body">
                                <h5 class="profile__contact-info-heading">E-mail address</h5>
                                <a href="mailto:admin@domain.com">admin@domain.com</a>
                            </div>
                        </div>*@
                </div>

            </div>
        </div>
    </div>

    @section scripts{

        <script src="~/lib/toastr/js/toastr.min.js"></script>

        <script src="~/js/Services/followsService.js"></script>
        <script src="~/js/Services/messagesService.js"></script>
        <script src="~/js/Controllers/followsController.js"></script>

        <script>
            $(document).ready(function () {
                FollowsController.enableFollows("#followbtn");
                FollowsController.enableMessaging("#messageBtn");
            });
        </script>

    }

GamersGrid/Views/GamerProfile/TestHub.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-typeahead/2.11.0/jquery.typeahead.css" integrity="sha512-AQG3JVpy/h0TsLsFs/HDLjnkq1ih9uUliGGXdQ7LQcGQt7GD+1b7HWOQ2oeCH7tKdtrfRg75CGApafi+//9Dbw==" crossorigin="anonymous" referrerpolicy="no-referrer" />

<input type="button" class="btn btn-primary" id="btnTest" name="name" value="" />


@section scripts {
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-typeahead/2.11.0/jquery.typeahead.js" integrity="sha512-hIaMZEgNK4DTnrqBvp0sV7bUhmT8hfbhT+6RQ3YX5e3x25xaH5W1kLi4KLAy16gKiebweip2Ng1udOYHSkBMBw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

    <script src="~/lib/signalr/dist/browser/signalr.js"></script>
    <script src="~/js/chatHub.js"></script>
    <script>
        $(document).ready(function () {
            $("#btnTest").on("click", function () {
                connection.invoke("Connect", "13");
            });



        });
    </script>
}

GamersGrid/Views/GamerProfile/UsersList.cshtml
@model IEnumerable<GamersGrid.DAL.Models.Identity.GGuser>

@{
    ViewBag.Title = "Index";
}

@section Styles {
    <link href="~/lib/JQueryDataTables/CSS/dataTables.min.css" rel="stylesheet" type="text/css" />
}

<h2>Users</h2>

<table id="users" class="table">
    <thead>
        <tr>
            <th>Nickname</th>
            <th>Country</th>
            <th>City</th>
        </tr>
    </thead>

</table>

@section scripts
{

    <script src="~/lib/JQueryDataTables/JS/dataTables.min.js"></script>

    <script>
        $(document).ready(function () {
            $("#users").DataTable({
                ajax: {
                    url: "/api/users?count=200",
                    dataSrc: ""
                },
                columns: [
                    {
                        data: "nickName",
                    },
                    {
                        data: "country",
                    },
                    {
                        data: "city",
                    }
                ]
            });
        });
    </script>
}